blank_issues_enabled: true

contact_links:
  - name: Ideas Discussion | 想法讨论
    url: https://github.com/Guovin/iptv-api/discussions/new?category=ideas
    about: Discuss an early-stage idea before submitting a formal feature request | 在提交正式功能建议前讨论初步想法

  - name: Support and Help | 使用问题与支持
    url: https://github.com/Guovin/iptv-api/discussions/categories/q-a
    about: Ask usage questions and get help here | 使用问题和答疑请前往这里
